server:
  port: 8092

spring:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop #엔티티 클래스를 기반으로 테이블을 자동 생성하고 세션이 끝나면 테이블을 제거하도록 설정
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver